name: Start cyrel-backend
on:
  schedule:
    - cron: '0 7 * * *'
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g clever-tools
        name: Install clever-tools
      - run: clever login --token $CLEVER_TOKEN --secret $CLEVER_SECRET
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
        name: Login
      - run: clever link $CLEVER_APP_ID
        env:
          CLEVER_APP_ID: ${{ secrets.CLEVER_APP_ID }}
        name: Link cyrel-backend app
      - run: clever restart
        name: Start cyrel-backend
        timeout-minutes: 30
